language: python
python:
  - "3.6"
#  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
  - sudo mkdir ./upload -p
  - sudo chmod 777 ./upload
  - sudo rm ./ustutor-debug.log
  - sudo touch ./ustutor-debug.log
  - sudo chmod 777 ./ustutor-debug.log
install:
  - pip install -r requirements.txt
  - export EXTERNALCFG=`pwd`/config/settings_travisci.cfg
  - chmod 777 ./dbinit_travisci.sh
  - ./dbinit_travisci.sh
# command to run tests
services:
  - mysql
script:
#  - pytest # or py.test for Python versions 3.5 and below
  - python -m unittest unittests/*.py
