language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379
install:
  - pip install -r requirements.txt
# command to run tests
services:
  - mysql
script:
#  - pytest # or py.test for Python versions 3.5 and below
  - python -m unittest unittests/*.py
